apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins-nm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          volumeMounts:
            - name: nfs-volume
              mountPath: /var/jenkins_home
      volumes:
        - name: nfs-volume
          nfs:
            server: 20.254.43.167
            path: /mnt/shared_directory
      # volumes:
      #   - name: jenkins-data
      #     emptyDir: {}
