apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: jenkins-nm
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/shared_directory
    server: 20.254.43.167
